# Generated by Django 5.0 on 2023-12-29 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_GERA', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='CatégorieProduit',
        ),
        migrations.DeleteModel(
            name='CatégorieProduit',
        ),
    ]
