# Generated by Django 4.2.10 on 2024-03-29 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_GERA', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilisateur',
            options={},
        ),
        migrations.AlterModelManagers(
            name='utilisateur',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='email',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='password',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='username',
        ),
    ]
