# Generated by Django 4.2.10 on 2024-02-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_GERA', '0003_commande_fraislivraison_commande_montanttotal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ville',
            name='Pays',
        ),
        migrations.AlterField(
            model_name='ville',
            name='Nom',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Pays',
        ),
    ]
