# Generated by Django 4.2.10 on 2024-02-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_GERA', '0006_auteurarticle_categorieevenement_evenement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='publie',
            field=models.BooleanField(default=False),
        ),
    ]
