# Generated by Django 4.2.10 on 2024-02-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_GERA', '0007_evenement_publie'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='evenement_images/'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='publie',
            field=models.BooleanField(default=True),
        ),
    ]
