# Generated by Django 4.2.10 on 2024-02-19 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_GERA', '0008_evenement_image_alter_evenement_publie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenement',
            name='Image',
        ),
    ]
