# Generated by Django 4.2.10 on 2024-02-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_GERA', '0009_remove_evenement_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='evenement_images/'),
        ),
    ]
