# Generated by Django 4.2.10 on 2024-02-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_GERA', '0010_evenement_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='Image',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
