# Generated by Django 4.2.10 on 2024-02-20 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_GERA', '0011_alter_evenement_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adresse',
            old_name='Quartier_ID',
            new_name='ID_Quartier',
        ),
        migrations.RenameField(
            model_name='quartier',
            old_name='QuartierID',
            new_name='ID_Quartier',
        ),
    ]
