# Generated by Django 4.2.10 on 2024-02-20 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_GERA', '0012_rename_quartier_id_adresse_id_quartier_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lieu',
            old_name='ID_Adresse',
            new_name='Adresse',
        ),
    ]
