# Generated by Django 4.2.10 on 2024-02-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_GERA', '0014_rename_id_quartier_adresse_quartier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='evenement_images/'),
        ),
    ]
