# Generated by Django 4.2.10 on 2024-03-14 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_GERA', '0015_alter_evenement_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosteDuPersonnel',
            fields=[
                ('ID_Poste', models.AutoField(primary_key=True, serialize=False)),
                ('Poste', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UtilisateurSimple',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_GERA.utilisateur')),
                ('Nom', models.CharField(max_length=50)),
                ('Prenom', models.CharField(max_length=50)),
                ('Tel', models.CharField(max_length=20, unique=True)),
            ],
            bases=('app_GERA.utilisateur',),
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_GERA.utilisateur')),
                ('Nom', models.CharField(max_length=50)),
                ('Prenom', models.CharField(max_length=50)),
                ('Tel', models.CharField(max_length=20, unique=True)),
                ('Poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_GERA.postedupersonnel')),
            ],
            bases=('app_GERA.utilisateur',),
        ),
    ]
