# Generated by Django 4.2.10 on 2024-03-14 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_GERA', '0016_postedupersonnel_utilisateursimple_personnel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='Role',
        ),
    ]
