# Generated by Django 4.2.10 on 2024-03-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_GERA', '0018_personnel_matricule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='Matricule',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
