# Generated by Django 4.2.10 on 2024-03-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_GERA', '0021_alter_personnel_matricule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='Mot_De_Passe',
            field=models.CharField(max_length=255),
        ),
    ]
