# Generated by Django 4.2.10 on 2024-03-20 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_GERA', '0022_alter_utilisateur_mot_de_passe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EvenementRessource',
        ),
    ]
