# Generated by Django 4.2.10 on 2024-03-20 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_GERA', '0023_delete_evenementressource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='ID_Categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_GERA.categorieevenement'),
        ),
    ]
