# Generated by Django 4.2.10 on 2024-03-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_GERA', '0024_alter_evenement_id_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='Email',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
