# Generated by Django 4.2.10 on 2024-03-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_GERA', '0027_alter_personnel_options_alter_utilisateur_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='Matricule',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='Tel',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='ID_Utilisateur',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='Mot_De_Passe',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='Nom_Utilisateur',
        ),
        migrations.RemoveField(
            model_name='utilisateursimple',
            name='Tel',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='Matricule',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='Tel',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
