# Generated by Django 4.2.10 on 2024-03-29 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_GERA', '0028_remove_personnel_matricule_remove_personnel_tel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='Poste',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='Poste',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_GERA.postedupersonnel'),
            preserve_default=False,
        ),
    ]
