# Generated by Django 4.2.10 on 2024-03-29 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_GERA', '0029_remove_personnel_poste_utilisateur_poste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateursimple',
            name='utilisateur_ptr',
        ),
        migrations.DeleteModel(
            name='Personnel',
        ),
        migrations.DeleteModel(
            name='UtilisateurSimple',
        ),
    ]
