# Generated by Django 4.2.10 on 2024-03-30 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_GERA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='Matricule_Personnel',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
