# Generated by Django 4.2.10 on 2024-03-30 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_GERA', '0003_utilisateur_mail_utilisateur_tel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='ID_Utilisateur',
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('ID_Membre', models.AutoField(default='', primary_key=True, serialize=False)),
                ('Nom_Utilisateur', models.CharField(max_length=50, unique=True)),
                ('Mot_De_Passe', models.CharField(default='', max_length=255)),
                ('Nom', models.CharField(max_length=50)),
                ('Prenom', models.CharField(max_length=50)),
                ('Matricule_Personnel', models.CharField(max_length=50, null=True)),
                ('Tel', models.CharField(max_length=20, null=True)),
                ('Mail', models.EmailField(max_length=254, null=True)),
                ('Poste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_GERA.postedupersonnel')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='inscriptionevenement',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='inscriptionevenement',
            name='ID_Membre',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app_GERA.membre'),
        ),
        migrations.AddField(
            model_name='notification',
            name='ID_Membre',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app_GERA.membre'),
        ),
        migrations.AlterUniqueTogether(
            name='inscriptionevenement',
            unique_together={('ID_Membre', 'ID_Evenement')},
        ),
        migrations.RemoveField(
            model_name='inscriptionevenement',
            name='ID_Utilisateur',
        ),
        migrations.DeleteModel(
            name='Utilisateur',
        ),
    ]
