# Generated by Django 4.2.10 on 2024-03-30 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_GERA', '0004_remove_notification_id_utilisateur_membre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeMembre',
            fields=[
                ('ID_Type', models.AutoField(primary_key=True, serialize=False)),
                ('Nom_Type', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='membre',
            name='Type_Membre',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app_GERA.typemembre'),
        ),
    ]
