# Generated by Django 4.2.10 on 2024-03-30 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_GERA', '0005_typemembre_membre_type_membre'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonnelEvenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_GERA.evenement')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_GERA.membre')),
            ],
        ),
    ]
