# Generated by Django 4.2.10 on 2024-03-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_GERA', '0006_personnelevenement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='Mot_De_Passe',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='membre',
            name='Nom',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='membre',
            name='Nom_Utilisateur',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='membre',
            name='Prenom',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
