# Generated by Django 4.2.10 on 2024-03-30 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_GERA', '0007_alter_membre_mot_de_passe_alter_membre_nom_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membre',
            old_name='Matricule_Personnel',
            new_name='Matricule',
        ),
    ]
