# Generated by Django 4.2.10 on 2024-03-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_GERA', '0008_rename_matricule_personnel_membre_matricule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='ID_Membre',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
