# Generated by Django 4.2.10 on 2024-03-31 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_GERA', '0009_alter_membre_id_membre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quartier',
            name='CodePostal',
        ),
        migrations.AddField(
            model_name='ville',
            name='CodePostal',
            field=models.CharField(default='', max_length=20),
        ),
    ]
