# Generated by Django 4.2.10 on 2024-04-03 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_GERA', '0013_organisateur_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='Date_Heure_Debut',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='Date_Heure_Fin',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='Description_Evenement',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='ID_Categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_GERA.categorieevenement'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='ID_Lieu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_GERA.lieu'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='ID_Organisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_GERA.organisateur'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='Titre_Evenenement',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='publie',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
