# Generated by Django 4.2.10 on 2024-04-04 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_GERA', '0015_typeevenement_evenement_id_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenement',
            name='ID_Type',
        ),
        migrations.AddField(
            model_name='categorieevenement',
            name='ID_Type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_GERA.typeevenement'),
        ),
    ]
