# Generated by Django 4.2.10 on 2024-04-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_GERA', '0017_alter_categorieevenement_id_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='publie',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
