# Generated by Django 4.2.10 on 2024-04-09 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_GERA', '0018_alter_evenement_publie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='Titre_Artcile',
            new_name='Titre_Article',
        ),
    ]
