# Generated by Django 4.2.10 on 2024-04-09 15:34

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('app_GERA', '0019_rename_titre_artcile_article_titre_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Contenu_Article',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
