# Generated by Django 4.2.10 on 2024-04-10 11:04

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_GERA', '0021_alter_article_contenu_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Contenu_Article',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Text'),
        ),
    ]
