# Generated by Django 4.2.10 on 2024-04-26 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_GERA', '0022_alter_article_contenu_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ressource',
        ),
    ]
