# Generated by Django 4.2.10 on 2024-04-26 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_GERA', '0023_delete_ressource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lieu',
            name='Capacite',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lieu',
            name='Disponibilite_Lieu',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
