# Generated by Django 4.2.10 on 2024-04-26 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_GERA', '0024_alter_lieu_capacite_alter_lieu_disponibilite_lieu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisateur',
            old_name='Description_organisateur',
            new_name='Description',
        ),
    ]
