# Generated by Django 4.2.10 on 2024-04-26 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_GERA', '0026_rename_ville_quartier_id_ville'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adresse',
            old_name='Quartier',
            new_name='ID_Quartier',
        ),
    ]
