# Generated by Django 4.2.10 on 2024-04-26 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_GERA', '0030_rename_description_evenement_evenement_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lieu',
            old_name='Adresse',
            new_name='ID_Adresse',
        ),
    ]
