# Generated by Django 4.2.10 on 2024-04-26 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_GERA', '0032_rename_poste_membre_id_poste'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membre',
            old_name='Type_Membre',
            new_name='ID_TypeMembre',
        ),
    ]
