# Generated by Django 4.2.10 on 2024-04-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_GERA', '0033_rename_type_membre_membre_id_typemembre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ville',
            name='CodePostal',
            field=models.CharField(max_length=20),
        ),
    ]
