# Generated by Django 4.2.10 on 2024-04-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_GERA', '0034_alter_ville_codepostal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisateur',
            name='Description',
            field=models.CharField(max_length=255),
        ),
    ]
