# Generated by Django 4.2.10 on 2024-04-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_GERA', '0035_alter_organisateur_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='auteurarticle',
            name='Prenom',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='auteurarticle',
            name='Nom',
            field=models.CharField(max_length=100),
        ),
    ]
