# Generated by Django 4.2.10 on 2024-04-26 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_GERA', '0036_auteurarticle_prenom_alter_auteurarticle_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auteurarticle',
            name='Prenom',
            field=models.CharField(max_length=100),
        ),
    ]
