# Generated by Django 4.2.10 on 2024-04-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_GERA', '0037_alter_auteurarticle_prenom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorieevenement',
            name='Categorie',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='organisateur',
            name='Mail',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='organisateur',
            name='Nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='organisateur',
            name='Prenom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='quartier',
            name='Nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='typeevenement',
            name='Nom_Type',
            field=models.CharField(max_length=50),
        ),
    ]
