# Generated by Django 4.2.10 on 2024-04-27 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_GERA', '0039_rename_organisateur_interlocuteur_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='publie_A',
            new_name='Publie_A',
        ),
    ]
