# Generated by Django 4.2.10 on 2024-05-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_GERA', '0040_rename_publie_a_article_publie_a'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='Date_Limite_Inscription',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='evenement',
            name='Inscription_E',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
