# Generated by Django 4.2.10 on 2024-05-10 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_GERA', '0041_evenement_date_limite_inscription_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adresse',
            table='Adresse',
        ),
        migrations.AlterModelTable(
            name='article',
            table='Article',
        ),
        migrations.AlterModelTable(
            name='auteurarticle',
            table='AuteurArticle',
        ),
        migrations.AlterModelTable(
            name='categorieevenement',
            table='CategorieEvenement',
        ),
        migrations.AlterModelTable(
            name='evenement',
            table='Evenement',
        ),
        migrations.AlterModelTable(
            name='inscriptionevenement',
            table='InscriptionEvenement',
        ),
        migrations.AlterModelTable(
            name='interlocuteur',
            table='Interlocuteur',
        ),
        migrations.AlterModelTable(
            name='lieu',
            table='Lieu',
        ),
        migrations.AlterModelTable(
            name='membre',
            table='Membre',
        ),
        migrations.AlterModelTable(
            name='notification',
            table='Notification',
        ),
        migrations.AlterModelTable(
            name='personnelevenement',
            table='PersonnelEvenement',
        ),
        migrations.AlterModelTable(
            name='postedupersonnel',
            table='PosteDuPersonnel',
        ),
        migrations.AlterModelTable(
            name='quartier',
            table='Quartier',
        ),
        migrations.AlterModelTable(
            name='typeevenement',
            table='TypeEvenement',
        ),
        migrations.AlterModelTable(
            name='typemembre',
            table='TypeMembre',
        ),
        migrations.AlterModelTable(
            name='ville',
            table='Ville',
        ),
    ]
