# Generated by Django 4.2.10 on 2024-05-11 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_GERA', '0042_alter_adresse_table_alter_article_table_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonnelEvenement',
        ),
    ]
