# Generated by Django 4.2.10 on 2024-05-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_GERA', '0044_alter_lieu_id_adresse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interlocuteur',
            name='Description_I',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='interlocuteur',
            name='Prenom_I',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
