# Generated by Django 4.2.10 on 2024-05-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_GERA', '0045_alter_interlocuteur_description_i_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='Date_E',
            field=models.DateField(null=True),
        ),
    ]
