# Generated by Django 5.0.6 on 2024-05-31 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_GERA', '0048_evenement_est_fait'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='Num_Audience',
            field=models.IntegerField(null=True),
        ),
    ]
