# Generated by Django 5.0.6 on 2024-06-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_GERA', '0049_evenement_num_audience'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='Est_Lu_Admin',
            field=models.BooleanField(default=False),
        ),
    ]
