# Generated by Django 5.0.6 on 2024-06-20 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_GERA', '0051_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
