# Generated by Django 5.0.6 on 2024-06-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_GERA', '0052_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='Description_E',
            field=models.TextField(null=True),
        ),
    ]
