# Generated by Django 5.0.6 on 2024-06-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_GERA', '0053_alter_evenement_description_e'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auteurarticle',
            name='Prenom_Auteur',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
